-- Run this migration in the Supabase SQL Editor, or with `supabase db push`.

create table public.learner_settings (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  sound_volume integer not null default 80,
  voice_feedback boolean not null default true,
  daily_reminders boolean not null default true,
  achievement_alerts boolean not null default true,
  dark_mode boolean not null default false,
  language text not null default 'Filipino',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_learner_settings_user on public.learner_settings(user_id);

create trigger learner_settings_updated_at before update on public.learner_settings
  for each row execute function public.set_updated_at();

alter table public.learner_settings enable row level security;
