-- Run this migration in the Supabase SQL Editor, or with `supabase db push`.
-- The Express API uses the service-role key, so keep that key server-side only.

create table public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('learner', 'teacher')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.learner_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  name text not null,
  avatar text not null default '🦊',
  grade integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.stages (
  id bigint generated by default as identity primary key,
  stage_number integer not null unique,
  title text not null,
  description text,
  difficulty integer not null default 1,
  created_at timestamptz not null default now()
);

create table public.levels (
  id bigint generated by default as identity primary key,
  stage_id bigint not null references public.stages(id) on delete cascade,
  level_number integer not null,
  title text not null,
  description text,
  target_phoneme text not null,
  difficulty integer not null default 1,
  created_at timestamptz not null default now(),
  unique(stage_id, level_number)
);

create table public.sessions (
  id bigint generated by default as identity primary key,
  learner_id bigint not null references public.learner_profiles(id) on delete cascade,
  level_id bigint not null references public.levels(id) on delete cascade,
  stage_id bigint not null references public.stages(id) on delete cascade,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'in_progress' check (status in ('in_progress', 'completed', 'abandoned'))
);

create table public.session_results (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  attempt_number integer not null default 1,
  transcription text,
  detected_phoneme text,
  target_phoneme text not null,
  score integer not null default 0,
  matched boolean not null default false,
  feedback text,
  created_at timestamptz not null default now()
);

create table public.progress (
  id bigint generated by default as identity primary key,
  learner_id bigint not null references public.learner_profiles(id) on delete cascade,
  stage_id bigint not null references public.stages(id) on delete cascade,
  completed_levels integer not null default 0,
  total_levels integer not null,
  completion_percentage integer not null default 0,
  last_updated timestamptz not null default now(),
  unique(learner_id, stage_id)
);

create table public.achievements (
  id bigint generated by default as identity primary key,
  learner_id bigint not null references public.learner_profiles(id) on delete cascade,
  achievement_type text not null,
  achievement_name text not null,
  description text,
  icon_emoji text,
  earned_at timestamptz not null default now()
);

create table public.characters (
  id bigint generated by default as identity primary key,
  name text not null unique,
  template text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.character_appearance (
  id bigint generated by default as identity primary key,
  character_id bigint not null unique references public.characters(id) on delete cascade,
  head_color text not null, head_shape text not null, eye_color text not null,
  eye_shape text not null, mouth_color text not null, accessories jsonb not null default '[]'::jsonb,
  body_color text not null
);

create table public.character_personality (
  id bigint generated by default as identity primary key,
  character_id bigint not null unique references public.characters(id) on delete cascade,
  personality_type text not null, animation_speed real not null, expression_style text not null
);

create table public.character_voice (
  id bigint generated by default as identity primary key,
  character_id bigint not null unique references public.characters(id) on delete cascade,
  voice_id text not null, pitch real not null, speed real not null, tone text not null, language text not null
);

create table public.character_behaviors (
  id bigint generated by default as identity primary key,
  character_id bigint not null references public.characters(id) on delete cascade,
  state text not null, animation_config jsonb not null, sound_effect text
);

create index idx_user_role on public.users(role);
create index idx_learner_user on public.learner_profiles(user_id);
create index idx_level_stage on public.levels(stage_id);
create index idx_session_learner on public.sessions(learner_id);
create index idx_session_level on public.sessions(level_id);
create index idx_result_session on public.session_results(session_id);
create index idx_progress_learner on public.progress(learner_id);
create index idx_achievement_learner on public.achievements(learner_id);
create index idx_character_behavior on public.character_behaviors(character_id, state);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger users_updated_at before update on public.users for each row execute function public.set_updated_at();
create trigger learner_profiles_updated_at before update on public.learner_profiles for each row execute function public.set_updated_at();
create trigger characters_updated_at before update on public.characters for each row execute function public.set_updated_at();

-- No browser client reads these tables directly. Enable RLS to prevent accidental
-- access through the anonymous key; the server service-role client bypasses it.
alter table public.users enable row level security;
alter table public.learner_profiles enable row level security;
alter table public.stages enable row level security;
alter table public.levels enable row level security;
alter table public.sessions enable row level security;
alter table public.session_results enable row level security;
alter table public.progress enable row level security;
alter table public.achievements enable row level security;
alter table public.characters enable row level security;
alter table public.character_appearance enable row level security;
alter table public.character_personality enable row level security;
alter table public.character_voice enable row level security;
alter table public.character_behaviors enable row level security;
