-- Run this migration in the Supabase SQL Editor, or with `supabase db push`.
-- Requires stages to already be seeded (see backend/scripts/seed.ts) so the
-- stage-exclusive frame rows link to the correct stage ids.

create table public.frames (
  id bigint generated by default as identity primary key,
  asset_key text not null unique,
  name text not null,
  unlock_stage_id bigint references public.stages(id) on delete set null,
  design_notes text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.user_unlocked_frames (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  frame_id bigint not null references public.frames(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  unique(user_id, frame_id)
);

alter table public.learner_profiles
  add column equipped_frame_id bigint references public.frames(id) on delete set null;

create index idx_frames_unlock_stage on public.frames(unlock_stage_id);
create index idx_user_unlocked_frames_user on public.user_unlocked_frames(user_id);

alter table public.frames enable row level security;
alter table public.user_unlocked_frames enable row level security;

-- Seed the two free default frames (unlock_stage_id null = available to everyone).
insert into public.frames (asset_key, name, unlock_stage_id, design_notes, sort_order) values
  ('sunrise-ring', 'Sunrise Ring', null, 'Soft cream-to-blush gradient ring, thin and simple. Neutral starter frame.', 1),
  ('indigo-classic', 'Indigo Classic', null, 'Simple gradient ring in Readlr brand indigo (#4F46E5 to #4338CA).', 2);

-- Seed one exclusive frame per stage.
insert into public.frames (asset_key, name, unlock_stage_id, design_notes, sort_order)
select 'star-trail-ring', 'Star Trail Ring', s.id,
  'Gold gradient ring studded with small star points around the rim, echoes the amber Valley of Vowels accent.', 10
from public.stages s where s.stage_number = 1;

insert into public.frames (asset_key, name, unlock_stage_id, design_notes, sort_order)
select 'lightning-bridge-ring', 'Lightning Bridge Ring', s.id,
  'Indigo-to-violet gradient ring with small zig-zag lightning bolt accents at the cardinal points, echoes the Blending Bridges accent.', 20
from public.stages s where s.stage_number = 2;

insert into public.frames (asset_key, name, unlock_stage_id, design_notes, sort_order)
select 'crown-jewel-ring', 'Crown Jewel Ring', s.id,
  'Emerald ring with gold trim and a small crown motif at the top, the prestige frame for finishing CVC Kingdom.', 30
from public.stages s where s.stage_number = 3;

-- Every existing and future user gets the free frames unlocked automatically.
insert into public.user_unlocked_frames (user_id, frame_id)
select u.id, f.id from public.users u
cross join public.frames f
where f.unlock_stage_id is null
on conflict do nothing;
